services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./docs/.vitepress/dist:/usr/share/caddy/vitepress
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:
